package com.fintech.superadmin.flight.util.common

object Constant {
    const val QR_CODE = "QR_CODE"
    const val PLAN = "PLAN"
    const val TypeAddress = "typeAddress"
    const val CityModel = "CityModel"
    const val FlightsItem = "FlightsItem"
    const val SearchKey = "SearchKey"
    const val PassengerJson = "PassengerJson"
    const val SelectedSeats = "SelectedSeats"
    const val SelectedTrip = "SelectedTrip"
    const val FromCityModel = "FromCityModel"
    const val TripId = "TripId"
    const val BpId = "BpId"
    const val DpId = "DpId"
    const val ToCityModel = "ToCityModel"
    const val Date = "Date"
    const val AllPrices = "All Prices"
    const val Response = "Response"
    const val CheckTicket = "CheckTicket"
    const val referenceID = "referenceID"
    const val AirPort = "AirPort"
    const val SelectedAirPort = "SelectedAirPort"
}